apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-volume-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/images"